# Generated by Django 4.0.4 on 2022-05-20 05:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('asset_hostname', models.CharField(blank=True, max_length=50, null=True, verbose_name='ASSET HOSTNAME')),
                ('asset_ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='ASSET IP ADDRESS')),
                ('vulnerability_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='VULNERABILITY TITLE')),
                ('vulnerability_severity', models.CharField(blank=True, max_length=200, null=True, verbose_name='VULNERABILITY SEVERITY')),
                ('vulnerability_cvss', models.CharField(blank=True, max_length=200, null=True, verbose_name='VULNERABILITY CVSS')),
                ('vulnerability_publication_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='VULNERABILITY PUBLICATION DATE')),
                ('is_fixed', models.BooleanField(default=False, verbose_name='IS FIXED')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
